dist: trusty
sudo: false

addons:
  apt:
    sources:
    - boost-latest
    - llvm-toolchain-trusty-3.9
    - ubuntu-toolchain-r-test
    packages:
    - libboost-all-dev
    - libclang-3.9-dev
    - llvm-3.9-dev
    - cmake
    - cmake-data
    - g++-5
    - gcc-5

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

language: cpp

compiler: gcc

script:
  - g++ --version
  - g++-5 --version
  - cmake --version
  - cd build_tools
  - cmake -DPROC_ALL=full_all -P .travis.cmake

after_script:
    - # ---------------------------------------------------------------------------------
    - cat /home/travis/build/yossi-tahara/build/gcc540x64-StaticWithBoost-Release/*.log
    - # ---------------------------------------------------------------------------------
    - cat /tmp/theolizer/Debug.log
    - # ---------------------------------------------------------------------------------
