##############################################################################
#   © 2016 Theoride Technology (http://theolizer.com/) All Rights Reserved.
#   "Theolizer" is a registered trademark of Theoride Technology.
#
#   "Theolizer" License
#       In the case where you are in possession of a valid “Theolizer” License,
#       you may use this file in accordance with the terms and conditions of 
#       the use license determined by Theoride Technology.
#
#   General Public License Version 3 ("GPLv3")
#       You may use this file in accordance with the terms and conditions of 
#       GPLv3 published by Free Software Foundation.
#       Please confirm the contents of GPLv3 at https://www.gnu.org/licenses/gpl.txt .
#       A copy of GPLv3 is also saved in a LICENSE.TXT file.
#
#   商用ライセンス
#       あなたが有効なTheolizer商用ライセンスを保持している場合、
#       セオライド テクノロジーの定める使用許諾書の条件に従って、
#       このファイルを取り扱うことができます。
#
#   General Public License Version 3(以下GPLv3)
#       Free Software Foundationが公表するGPLv3の使用条件に従って、
#       あなたはこのファイルを取り扱うことができます。
#       GPLv3の内容を https://www.gnu.org/licenses/gpl.txt にて確認して下さい。
#       またGPLv3のコピーをLICENSE.TXTファイルにおいてます。
##############################################################################

dist: trusty
sudo: false
language: cpp
compiler: gcc

cache:
  directories:
  - $TRAVIS_BUILD_DIR/../build/boost/1.59.0/gcc540x64
  - $TRAVIS_BUILD_DIR/../build/boost/1.59.0/install64

addons:
  apt:
    sources:
    - llvm-toolchain-trusty-4.0
    - ubuntu-toolchain-r-test
    packages:
    - libclang-4.0-dev
    - llvm-4.0-dev
    - cmake
    - cmake-data
    - g++-5
    - gcc-5

env:
  matrix:
    - PARALLEL_TEST=1
    - PARALLEL_TEST=2
    - PARALLEL_TEST=3

before_install:
  - g++ --version
  - g++-5 --version
  - cmake --version

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - echo '================================================================================='
  - ls -l $TRAVIS_BUILD_DIR/../build/boost/1.59.0
  - ls -l $TRAVIS_BUILD_DIR/../build/boost/1.59.0/gcc540x64
  - ls -l $TRAVIS_BUILD_DIR/../build/boost/1.59.0/install64
  - echo '================================================================================='
  - cd build_tools
  - cmake -DPROC_ALL=full_all -P .travis.cmake

after_script:
  - echo '================================================================================='
  - ls -l $TRAVIS_BUILD_DIR/../build/boost/1.59.0
  - ls -l $TRAVIS_BUILD_DIR/../build/boost/1.59.0/gcc540x64
  - ls -l $TRAVIS_BUILD_DIR/../build/boost/1.59.0/install64
#  - echo '---------------------------------------------------------------------------------'
#  - cat $TRAVIS_BUILD_DIR/../build/gcc540x64-StaticWithBoost-Release/*.log
#  - echo '---------------------------------------------------------------------------------'
#  - cat $TRAVIS_BUILD_DIR/../build/gcc540x64-Static-Release/*.log
#  - echo '---------------------------------------------------------------------------------'
#  - cat $TRAVIS_BUILD_DIR/../build/gcc540x64-Shared-Release/*.log
#  - echo '---------------------------------------------------------------------------------'
#  - cat $TRAVIS_BUILD_DIR/../build/gcc540x64-StaticWithBoost-Release/reference_and_test/version/basic/*.hpp
  - echo '================================================================================='
