addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.9
    packages:
    - libclang-3.9-dev
    - llvm-3.9-dev

language: cpp

compiler: gcc

script:
  - cmake --version
  - cd build_tools
  - cmake -DPROC_ALL=full_all -P .travis.cmake
