addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost-all-dev

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.9
    packages:
    - libclang-3.9-dev
    - llvm-3.9-dev

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data

language: cpp

compiler: gcc

script:
  - cmake --version
  - cd build_tools
  - cmake -DPROC_ALL=full_all -P .travis.cmake
