addons:
  apt:
    sources:
    - boost-latest
    - george-edison55-precise-backports
    packages:
    - libboost-all-dev
    - cmake
    - cmake-data

language: cpp

compiler: gcc

script:
  - cmake --version
  - cd build_tools
  - cmake -DPROC_ALL=full_all -P .travis.cmake
