addons:
  apt:
    sources:
    - boost-latest
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - libboost-all-dev
    - cmake
    - cmake-data
    - g++-5
    - libclang-3.8-dev
    - llvm-3.8-dev

language: cpp

compiler: gcc

script:
  - cmake --version
  - cd build_tools
  - cmake -DPROC_ALL=full_all -P .travis.cmake
