addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost-all-dev

language: cpp

compiler: gcc

script:
  - cmake --version
  - cd build_tools
  - cmake -DPROC_ALL=full_all -P .travis.cmake
